apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: akaunting
  namespace: akaunting
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`consulting.rmblau.com`)
      services:
        - name: akaunting
          port: 80
  tls:
    certResolver: letsencrypt-dns01-issuer
