apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key
  namespace: traefik
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore

  target:
    name: cloudflare-api-key
    creationPolicy: Owner
    template:
      type: Opaque

  data:
    - secretKey: api-key
      remoteRef:
        key: 6baf4645-2e13-4d63-b040-b2eb00220d66
        property: api-key