apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key-secret
  namespace: traefik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-key-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: cloudflare-api-key-secret
      remoteRef:
        key: 99355dc5-5e16-4b5f-9a95-b4bc0013d143
        property: password